cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:123}
      secret-key: ${AWS_SECRET_KEY:123}
    region:
      static: ${AWS_REGION:eu-north-1}
    stack:
      auto: false

application:
  bucket:
    name: ${AWS_BUCKET_NAME:wulal}

server:
  port: ${PORT:8000}
